site_name: nicomedkey.cc Docs
repo_name: uboar/nicomedkey-docs

theme:
  name: material
  language: ja
  logo: https://s3.ap-northeast-1.wasabisys.com/s3.nicomedkey.cc/public/logo_kari2.png
  favicon: https://s3.ap-northeast-1.wasabisys.com/s3.nicomedkey.cc/public/logo_kari2.png
  font:
    text: Kosugi Maru

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://nicomedkey.cc

nav:
  - 利用規約: index.md

